### ISSUE TITLE
Add pretty pictures

### ISSUE THREAD

**Issue by cheapjack** [radames/Minecraft-Solar-Explorations#2]

**Comment by cheapjack** [comment]
![solar](https://cloud.githubusercontent.com/assets/128456/13730043/cd19f562-e93b-11e5-8648-b81b2ddc1409.png)

**Comment by radames** [comment]
Pictures from our actual model

<img width="1442" alt="sun" src="https://cloud.githubusercontent.com/assets/102277/13762785/3ac244fe-ea39-11e5-9433-e9ccdb634127.png">
<img width="1442" alt="first_planets" src="https://cloud.githubusercontent.com/assets/102277/13762786/3ac3c7d4-ea39-11e5-9d4b-7f1ef96f36ee.png">
